name: RDP-and-Drive-BiSync-Secondary

on:
  workflow_dispatch:
    inputs:
      triggered_by:
        required: true
      loop_id:
        required: true
  schedule:
    - cron: '0 6,12,18 * * *'  # Every 6, 12, and 18 UTC

jobs:
  setup:
    runs-on: windows-latest
    timeout-minutes: 390  # 6.5 hours
    env:
      LOOP_ID: secondary
      RDP_USER: 'RDP'
      RDP_PASS: ${{ secrets.RDP_PASS }}
      TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
      TAILSCALE_API_TOKEN: ${{ secrets.TAILSCALE_API_TOKEN }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      GOOGLE_TOKEN: ${{ secrets.GOOGLE_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Chocolatey packages
        uses: actions/cache@v3
        with:
          path: C:\ProgramData\chocolatey\lib
          key: ${{ runner.os }}-choco-cache-secondary

      - name: Install Chocolatey and Tools
        shell: pwsh
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
          choco install tailscale rclone vmwareworkstation -y --no-progress

      - name: Configure RDP user and permissions (SECONDARY)
        shell: pwsh
        run: |
          # Enable RDP and disable Network Level Auth
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name 'fDenyTSConnections' -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name 'UserAuthentication' -Value 0 -Force
          netsh advfirewall firewall add rule name=RDP protocol=TCP dir=in localport=3389 action=allow
          Restart-Service TermService -Force

          # Create or update RDP user
          $securePass = ConvertTo-SecureString $env:RDP_PASS -AsPlainText -Force
          if (-not (Get-LocalUser -Name $env:RDP_USER -ErrorAction SilentlyContinue)) {
            New-LocalUser -Name $env:RDP_USER -Password $securePass -FullName 'Remote User' -ErrorAction Stop
          } else {
            Set-LocalUser -Name $env:RDP_USER -Password $securePass -ErrorAction Stop
          }

          # Add to Administrators and Remote Desktop Users
          Add-LocalGroupMember -Group 'Administrators' -Member $env:RDP_USER -ErrorAction Stop
          Add-LocalGroupMember -Group 'Remote Desktop Users' -Member $env:RDP_USER -ErrorAction Stop

          echo "RDP_USER=$env:RDP_USER" >> $env:GITHUB_ENV
          echo "RDP_PASS=$env:RDP_PASS" >> $env:GITHUB_ENV

          Write-Host "✅ RDP user configured (SECONDARY)"

      - name: Start and approve Tailscale (SECONDARY)
        shell: pwsh
        run: |
          & "$env:ProgramFiles\Tailscale\tailscale.exe" up --authkey=$env:TAILSCALE_AUTH_KEY --hostname="gh-rdp-secondary-$env:GITHUB_RUN_ID"
          for ($i = 0; $i -lt 12; $i++) {
            Start-Sleep -Seconds 5
            $ip = & "$env:ProgramFiles\Tailscale\tailscale.exe" ip -4
            if ($ip) { break }
          }
          echo "TAILSCALE_IP=$ip" >> $env:GITHUB_ENV

          if ($env:TAILSCALE_API_TOKEN) {
            $node = ( & "$env:ProgramFiles\Tailscale\tailscale.exe" status --json | ConvertFrom-Json ).Self.ID
            if ($node) {
              $hdr = @{ Authorization = "Bearer $env:TAILSCALE_API_TOKEN"; 'Content-Type' = 'application/json' }
              Invoke-RestMethod "https://api.tailscale.com/api/v2/device/$node/authorized" -Method Post -Headers $hdr -Body '{"authorized":true}'
              Write-Host "✅ Tailscale device approved (SECONDARY)"
            }
          }

          Write-Host "✅ Tailscale started at IP $ip (SECONDARY)"

      - name: Show connection info (SECONDARY)
        shell: pwsh
        run: |
          Write-Host "`n🎯 RDP CONNECTION DETAILS (SECONDARY):"
          Write-Host "========================================"
          Write-Host "Tailscale IP: $env:TAILSCALE_IP"
          Write-Host "User: $env:RDP_USER / $env:RDP_PASS"
          Write-Host "Connect via Android or mstsc.exe"
          Write-Host "Session: SECONDARY - 5 hours active, main starts with 30m left"
          Write-Host "========================================"

      - name: Configure rclone for Google Drive (SECONDARY)
        shell: pwsh
        run: |
          $cfg = "$env:USERPROFILE\.config\rclone"
          if (!(Test-Path $cfg)) { New-Item $cfg -ItemType Directory -Force }
          @"
          [gdrive]
          type = drive
          client_id = $env:GOOGLE_CLIENT_ID
          client_secret = $env:GOOGLE_CLIENT_SECRET
          scope = drive
          token = $env:GOOGLE_TOKEN
          "@ | Set-Content "$cfg\rclone.conf"
          Write-Host "✅ rclone configured (SECONDARY)"

      - name: Create VMware config.ini (SECONDARY)
        shell: pwsh
        run: |
          $dir = "$env:APPDATA\VMware"
          if (!(Test-Path $dir)) { New-Item $dir -ItemType Directory -Force }
          New-Item "$dir\config.ini" -ItemType File -Force
          icacls "$dir" /grant "$env:RDP_USER:(OI)(CI)F" /T
          Write-Host "✅ VMware config.ini created (SECONDARY)"

      - name: Download storage to Desktop\persistent (SECONDARY)
        shell: pwsh
        run: |
          $dst = "$env:USERPROFILE\Desktop\persistent"
          if (!(Test-Path $dst)) { New-Item $dst -ItemType Directory -Force }
          rclone copy gdrive:/storage $dst --config "$env:USERPROFILE\.config\rclone\rclone.conf" --drive-acknowledge-abuse --drive-skip-gdocs --retries 3 --timeout 10m --verbose
          Write-Host "✅ Storage downloaded (SECONDARY)"

      - name: Grant persistent folder permissions (SECONDARY)
        shell: pwsh
        run: |
          icacls "$env:USERPROFILE\Desktop\persistent" /grant "$env:RDP_USER:(OI)(CI)F" /T
          Write-Host "✅ Permissions set (SECONDARY)"

      - name: Wait until 5h30m for main workflow start (SECONDARY)
        shell: pwsh
        run: |
          Write-Host "⏳ SECONDARY: Waiting 5h30m before starting main workflow..."
          Start-Sleep -Seconds 19800

      - name: Trigger main workflow (30m left) (SECONDARY)
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'main.yaml',
              ref: 'main',
              inputs: { triggered_by: 'main2', loop_id: 'secondary' }
            })
            console.log('✅ Main workflow triggered with 30m left (from SECONDARY)')

      - name: Wait remaining 30m then sync (SECONDARY)
        shell: pwsh
        run: |
          Write-Host "⏳ SECONDARY: Waiting final 30m before sync..."
          Start-Sleep -Seconds 1800

      - name: Run final bi-directional sync (SECONDARY)
        shell: pwsh
        run: |
          $loc = "$env:USERPROFILE\Desktop\persistent"
          rclone bisync $loc gdrive:/storage --config "$env:USERPROFILE\.config\rclone\rclone.conf" --drive-acknowledge-abuse --drive-skip-gdocs --resync --resilient --create-empty-src-dirs --retries 3 --timeout 15m --verbose
          Write-Host "✅ Final sync complete (SECONDARY)"

      - name: Session complete summary (SECONDARY)
        shell: pwsh
        run: |
          Write-Host "`n🎯 SECONDARY SESSION COMPLETE:"
          Write-Host "-------------------------------"
          Write-Host "🔄 Main workflow started with 30m remaining"
          Write-Host "✅ Final sync done at $(Get-Date)"
          Write-Host "🔄 Main workflow will handle next cycle"
          Write-Host "==============================="
