name: RDP-and-Drive-BiSync-Main-Automated

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours

jobs:
  rdp_bisync:
    runs-on: windows-latest
    timeout-minutes: 390  # 6.5 hours
    env:
      RDP_USER: 'RDP'
      RDP_PASS: ${{ secrets.RDP_PASS }}
      TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
      TAILSCALE_API_TOKEN: ${{ secrets.TAILSCALE_API_TOKEN }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      GOOGLE_TOKEN: ${{ secrets.GOOGLE_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Chocolatey packages
        uses: actions/cache@v3
        with:
          path: C:\ProgramData\chocolatey\lib
          key: ${{ runner.os }}-choco-cache

      - name: Install Chocolatey and Tools
        shell: pwsh
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
          choco install tailscale rclone -y --no-progress

      - name: Configure RDP user and permissions
        shell: pwsh
        run: |
          # Enable RDP and disable NLA
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name 'fDenyTSConnections' -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name 'UserAuthentication' -Value 0 -Force
          netsh advfirewall firewall add rule name=RDP protocol=TCP dir=in localport=3389 action=allow
          Restart-Service TermService -Force

          # Create or update RDP user
          $securePass = ConvertTo-SecureString $env:RDP_PASS -AsPlainText -Force
          if (-not (Get-LocalUser -Name $env:RDP_USER -ErrorAction SilentlyContinue)) {
            New-LocalUser -Name $env:RDP_USER -Password $securePass -FullName 'Remote User' -ErrorAction Stop
          } else {
            Set-LocalUser -Name $env:RDP_USER -Password $securePass -ErrorAction Stop
          }

          # Add to groups
          Add-LocalGroupMember -Group 'Administrators' -Member $env:RDP_USER -ErrorAction Stop
          Add-LocalGroupMember -Group 'Remote Desktop Users' -Member $env:RDP_USER -ErrorAction Stop

          echo "RDP_USER=$env:RDP_USER" >> $env:GITHUB_ENV
          echo "RDP_PASS=$env:RDP_PASS" >> $env:GITHUB_ENV

      - name: Start and approve Tailscale
        shell: pwsh
        run: |
          & "$env:ProgramFiles\Tailscale\tailscale.exe" up --authkey=$env:TAILSCALE_AUTH_KEY --hostname="gh-rdp-main-$env:GITHUB_RUN_ID"
          for ($i = 0; $i -lt 12; $i++) {
            Start-Sleep -Seconds 5
            $ip = & "$env:ProgramFiles\Tailscale\tailscale.exe" ip -4
            if ($ip) { break }
          }
          echo "TAILSCALE_IP=$ip" >> $env:GITHUB_ENV

          if ($env:TAILSCALE_API_TOKEN) {
            $node = ( & "$env:ProgramFiles\Tailscale\tailscale.exe" status --json | ConvertFrom-Json ).Self.ID
            if ($node) {
              $hdr = @{ Authorization = "Bearer $env:TAILSCALE_API_TOKEN"; 'Content-Type' = 'application/json' }
              Invoke-RestMethod "https://api.tailscale.com/api/v2/device/$node/authorized" -Method Post -Headers $hdr -Body '{"authorized":true}'
            }
          }

      - name: Show connection info
        shell: pwsh
        run: |
          Write-Host "`n🎯 RDP CONNECTION DETAILS:"
          Write-Host "==========================="
          Write-Host "Tailscale IP: $env:TAILSCALE_IP"
          Write-Host "User: $env:RDP_USER / $env:RDP_PASS"
          Write-Host "Connect via Android or mstsc.exe"
          Write-Host "Session: 5 hours active, secondary starts with 30m left"
          Write-Host "==========================="

      - name: Configure rclone for Google Drive
        shell: pwsh
        run: |
          $cfg = "$env:USERPROFILE\.config\rclone"
          if (!(Test-Path $cfg)) { New-Item $cfg -ItemType Directory -Force }
          @"
          [gdrive]
          type = drive
          client_id = $env:GOOGLE_CLIENT_ID
          client_secret = $env:GOOGLE_CLIENT_SECRET
          scope = drive
          token = $env:GOOGLE_TOKEN
          "@ | Set-Content "$cfg\rclone.conf"

      - name: Download storage to Desktop\persistent
        shell: pwsh
        run: |
          $dst = "C:\Users\runneradmin\Desktop\persistent"
          if (!(Test-Path $dst)) { New-Item $dst -ItemType Directory -Force }
          rclone copy gdrive:/storage $dst --config "$env:USERPROFILE\.config\rclone\rclone.conf" --drive-acknowledge-abuse --drive-skip-gdocs --retries 3 --timeout 10m --verbose

      - name: Grant persistent folder permissions
        shell: pwsh
        run: |
          icacls "C:\Users\runneradmin\Desktop\persistent" /grant "$env:RDP_USER:(OI)(CI)F" /T

      - name: Install VMware Workstation from cloned EXE
        shell: pwsh
        run: |
          $exePath = "C:\Users\runneradmin\Desktop\persistent\VMware-workstation-full-17.6.4-24832109.exe"
          if (Test-Path $exePath) {
            Start-Process -FilePath $exePath `
                          -ArgumentList '/S','/v"/qn ADDLOCAL=All"' `
                          -Wait `
                          -NoNewWindow `
                          -Verb RunAs
          } else {
            Write-Warning "VMware installer not found at $exePath"
          }

      - name: Wait until 5h30m for secondary start
        shell: pwsh
        run: |
          Start-Sleep -Seconds 19800

      - name: Trigger secondary workflow (30m left)
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'main2.yaml',
              ref: 'main',
              inputs: { triggered_by: 'main', loop_id: 'main' }
            })

      - name: Wait remaining 30m then sync
        shell: pwsh
        run: |
          Start-Sleep -Seconds 1800

      - name: Run final bi-directional sync
        shell: pwsh
        run: |
          $loc = "C:\Users\runneradmin\Desktop\persistent"
          rclone bisync $loc gdrive:/storage --config "$env:USERPROFILE\.config\rclone\rclone.conf" --drive-acknowledge-abuse --drive-skip-gdocs --resync --resilient --create-empty-src-dirs --retries 3 --timeout 15m --verbose

      - name: Session complete summary
        shell: pwsh
        run: |
          Write-Host "`n🎯 MAIN SESSION COMPLETE:"
          Write-Host "---------------------------"
          Write-Host "🔄 Secondary started with 30m remaining"
          Write-Host "✅ Final sync done at $(Get-Date)"
          Write-Host "🔄 Secondary workflow will handle next cycle"
          Write-Host "==============================="
